This notebook is for reviewing the results of the analyses that Kshamaa and Pablo have done.

In [1]:
import pandas as pd

# Checking Q-values 
The computed ones vs. those that are output by RenEEL.

In [2]:
# load the Q-value data
q_values_computed = pd.read_csv('q_values_computed.csv')
q_values_computed.head()

       bodyId  in_degree   Q_value
0   729621875      404.0  0.171527
1   487144598      707.0  0.246586
2  1672320134      405.0  0.008361
3   550426732      335.0  0.171322
4  5813132515      294.0  0.165855

Why doesn't reneel_q_values.csv exist in the repo when the spatial_clustering_Kshamaa_V3.ipynb file appears to save the Q-values from RenEEL with that name? Does qvalue_analysis.csv have the Q-values from RenEEL?

In [5]:
# load the Q-values from RenEEL
q_values_reneel = pd.read_csv('qvalue_analysis.csv')
#q_values_reneel = pd.read_csv('reneel_q_values.csv')
q_values_reneel.head()

       bodyId  in_degree   Q_value   in_degree_bin
0   729621875      404.0  0.171527  (387.0, 426.8]
1   487144598      707.0  0.246586  (611.2, 885.8]
2  1672320134      405.0  0.008361  (387.0, 426.8]
3   550426732      335.0  0.171322  (326.7, 347.6]
4  5813132515      294.0  0.165855  (292.0, 304.8]

In [6]:
len(q_values_computed), len(q_values_reneel)

(500, 500)

In [8]:
# Merge the two DataFrames on 'bodyId' to compare Q-values
comparing_q_values = pd.merge(q_values_computed[['bodyId','Q_value']], q_values_reneel[['bodyId','Q_value']], on='bodyId', suffixes=('_computed', '_reneel'))

# subtract the Q-values to see the difference
comparing_q_values['Q_value_difference'] = comparing_q_values['Q_value_computed'] - comparing_q_values['Q_value_reneel']

# show any non-zero differences
comparing_q_values[comparing_q_values['Q_value_difference'] != 0]

Empty DataFrame
Columns: [bodyId, Q_value_computed, Q_value_reneel, Q_value_difference]
Index: []

# Spot checking